### ISSUE TITLE
VS Build Error

### ISSUE THREAD

**Issue by vortex1409** [TheOpenFlare/OpenFlareClient#2]
Project will not build in Visual Studio Community 2015 x64
`
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: OpenFlareClient, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\NotifyIconWpf.csproj' does not exist.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\Sharp.Xmpp\Sharp.Xmpp.csproj' does not exist.
1>C:\Users\vortex1409\Downloads\OpenFlareClient-master\OpenFlareClient\OF_MainWindow.xaml(40,10): error MC3074: The tag 'TaskbarIcon' does not exist in XML namespace 'http://www.hardcodet.net/taskbar'. Line 40 Position 10.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by poqdavid** [comment]
just get https://www.microsoft.com/en-us/download/details.aspx?id=49978 and make sure you use git to clone the project or once you get the zip make sure you check the local content of the repo with remote repo
