### ISSUE TITLE
Loading... Offline User

### ISSUE THREAD

**Issue by vortex1409** [TheOpenFlare/OpenFlareClient#3]
When login occurs any offline user has their username shown as Loading....
![image](https://cloud.githubusercontent.com/assets/4574867/18361664/be54675c-75d0-11e6-955d-88c3c9c8f6d9.png)

**Comment by poqdavid** [comment]
i know this is because there is no nick set in vcard i will fix it

**Comment by vortex1409** [comment]
Has this been resolved in the last update?

**Comment by poqdavid** [comment]
yap
